const CONSTANTS = {
  GET_CITIES: "GET_CITIES",
  SET_CITIES: "SET_CITIES",

  GET_REGIONS: "GET_REGIONS",
  SET_REGIONS: "SET_REGIONS",

  GET_REAL_ESTATES: "GET_REAL_ESTATES",
  SET_REAL_ESTATES: "SET_REAL_ESTATES",

  GET_AGENTS: "GET_AGENTS",
  SET_AGENTS: "SET_AGENTS",

  GET_ESTATE_BY_ID: "GET_ESTATE_BY_ID",
  SET_SELECTED_ESTATE: "SET_SELECTED_ESTATE",

  GET_FILTERS: "GET_FILTERS",
  SET_FILTERS: "SET_FILTERS",

  SET_FILTERED_LIST: "SET_FILTERED_LIST",

  UPDATE_REGION: "UPDATE_REGION",

  GET_CREATE_AGENTS: "GET_CREATE_AGENTS",
  SET_CREATE_AGENTS: "SET_CREATE_AGENTS",

  GET_CREATE_ESTATE: "GET_CREATE_ESTATE",
  SET_CREATE_ESTATE: "SET_CREATE_ESTATE",

  REMOVE_ESTATE: "REMOVE_ESTATE",
  DELETE_ESTATE: "DELETE_ESTATE",

  CLEAR_FILTERS: "CLEAR_FILTERS",

  CLEAR_INDIVIDUAL_FILTER: "CLEAR_INDIVIDUAL_FILTER"
};

export default CONSTANTS;
